name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx (enables advanced caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # 4️⃣ Build and push Docker image with optimized caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/ranazaeem0/zaeem_bot:latest
            ghcr.io/ranazaeem0/zaeem_bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5️⃣ Deploy notification (optional)
      - name: Deployment summary
        if: success() && github.event_name == 'push'
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "📦 Image: ghcr.io/ranazaeem0/zaeem_bot:latest"
          echo "🔖 SHA: ghcr.io/ranazaeem0/zaeem_bot:${{ github.sha }}"
